services:
  db:
    image: postgres:17
    container_name: sats-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: capstone
      POSTGRES_PASSWORD: 2025
      POSTGRES_DB: sats
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped
