import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    headerIcon: {
        width: 14,
        height: 14,
        marginRight: 10, 
        resizeMode: 'contain',
    },
    horizontalLine: {
        width: '100%',
        height: 2,
        backgroundColor: '#BCBBBB',
        marginVertical: 5,
    },
    popup: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.20)', // Semi-transparent background
    },
    popupBox: {
        width: '40%',
        height: '45%',
        backgroundColor: 'white',
        borderRadius: 10,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: 10,
    },
    popupHeader: {
        width: '100%',
        height: 50,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        backgroundColor: '#E8E7E7',
        paddingLeft: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.5,
        shadowRadius: 3,
        elevation: 3,
    },
    popupBody: {
        flex: 1,
        width: '100%',
        padding: 20,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
    },
    popupBodyRow: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
    },
    popupClose: {
        width: 40,
        height: 40,
        padding: 5,
    },
    popupIcon: {
        width: 30,
        height: 30,
        marginRight: 10,
        resizeMode: 'contain',
    },
    popupTitle: {
        fontSize: 18,
        fontFamily: 'Lato',
        fontWeight: 'bold',
        textTransform: 'uppercase',
        color: '#3e2b2f',
    },
    popupSubtitle: {
        fontSize: 18,
    },
    popupText: {
        fontSize: 16,
    },
    popupTextInput: {
        width: '100%', 
        height: 40,
        borderColor: '#007852',
        borderWidth: 1,
        borderRadius: 8,
        paddingLeft: 10,
    },
    picker: {
        width: '100%', 
        height: 40,
        borderColor: '#007852',
        borderWidth: 1,
        borderRadius: 8,
        paddingLeft: 10,
    },

    // MANAGE USERS ------------------------------------
    userContainer:{
        flex: 1,
        width: '100%',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: 20,
    },
    userHeader: {
        width: '100%',
        borderRadius: 4,
        padding: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        backgroundColor: '#F2F1F1',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    userBody: {
        flex: 1,
        width: '100%',
        borderRadius: 4,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'flex-start',
        backgroundColor: '#F2F1F1',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    userScroll: {
        flex: 1,
        width: '100%',
        padding: 10,
    },
    userButton: {
        width: 125,
        borderRadius: 8,
        padding: 5,
        backgroundColor: '#0B8261',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.5,
        shadowRadius: 4,
        elevation: 3,
    },
    userButtonText: {
        fontSize: 14,
        fontFamily: 'Lato',
        color: '#E1FFED',
        textTransform: 'uppercase',
        fontWeight: 'bold',
    },

    newUserBox: {
        width: '100%',
        padding: 10,
        borderRadius: 10,
        flexDirection: 'column',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
        gap: 5,
        backgroundColor: '#ffffff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
        marginBottom: 15,
    },
    newUserHeader: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    newUserTitle: {
        fontSize: 20,
        fontFamily: 'Lato',
        color: '#000',
    },
    newUserButtons: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
    },
    newUserButton: {
        width: 40,
        height: 40,
        padding: 5,
    },
    newUserButtonIcon: {
        width: 30,
        height: 30,
        marginRight: 10,
        resizeMode: 'contain',
    },
    newUserText: {
        fontSize: 16,
        fontFamily: 'Lato',
        color: '#000',
    },


    // MANAGE REASONS ----------------------------------
});

export default styles;
  