name: "Build Android app"

on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        if: github.event.head_commit.message != 'Merge branch'
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        if: github.event.head_commit.message != 'Merge branch'
        run: npm install

      - name: Setup JDK 17
        if: github.event.head_commit.message != 'Merge branch'
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install Android SDK
        if: github.event.head_commit.message != 'Merge branch'
        uses: android-actions/setup-android@v2
        with:
          api-level: 35
          build-tools-version: 35.0.0

      - name: Build Android App
        if: github.event.head_commit.message != 'Merge branch'
        run: cd ./android && ./gradlew assembleRelease

      - name: Upload APK
        if: github.event.head_commit.message != 'Merge branch'
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
